server:
  port: 8181
spring:
  config:
    import:
      - telegram-config.yml
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=housemarketplace
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql
    hibernate:
      ddl-auto: create-drop
    generate-ddl: true