telegram:
  #  api-url: "https://api.telegram.org/"
  proxy:
    host: "10.3.254.50"
    port: 3128
  bot:
    house-marketplace:
      name: "CommerceBot"
      token: "6933511415:AAGVslXnvBNEd5cKJHg7tQNueTjpFKdwRXE"
